In [2]:
import torch

List of tuple and list of list
```python
torch.tensor([1], [2]) #is a tuple of lists.
torch.tensor[[1], [2]] #is a list of lists.
```

In [ ]:
one_d = torch.tensor([1,2]) # 1 D
two_d = torch.tensor(([1], [2]))  # 2 D, tuple
one_d_array = torch.tensor([[1,2]]) # array of 2 D, 1 row two columns
print(one_d.shape) # 
print(two_d.shape) # two rows one column
print(one_d_array.shape)

torch.Size([2])
torch.Size([2, 1])
torch.Size([1, 2])


In [18]:
print(one_d.ndim)
print(two_d.ndim)
print(one_d_array.ndim)

1
2
2


In [14]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
import numpy as np

x = np.array([[10,20,30], [1,2,3]])
print(x.shape)

y = torch.tensor(x)
print(y.shape)



(2, 3)
torch.Size([2, 3])


In [46]:
x = torch.tensor([[1,2,3], [2,2,2], [3,3,3]])
y = torch.tensor([[1,2,3], [2,2,2], [3,3,3]])


print(x.shape)
print(y.shape)

x @ y

torch.Size([3, 3])
torch.Size([3, 3])


tensor([[14, 15, 16],
        [12, 14, 16],
        [18, 21, 24]])

In [44]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

result = a @ b  # Matrix multiplication

print(result)
# Output:
# tensor([[19, 22],
#         [43,

tensor([[19, 22],
        [43, 50]])


In [61]:
# Simple way to calc gradient

x = torch.tensor([[2., -3.][1., 1.]], requires_grad = True)
#torch.tensor([[2., -1.], [1., 1.]], requires_grad=True)
print(x)


<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\ppoob\AppData\Local\Temp\ipykernel_11040\1023373341.py:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x = torch.tensor([[2., -3.][1., 1.]], requires_grad = True)


TypeError: list indices must be integers or slices, not tuple

In [51]:
out = x.pow(2).sum()
out.backward()
print(x.grad)

tensor([4.])
